# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Contributors to Eclipse OpenSOVD (see CONTRIBUTORS)
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0

name: Nightly Advisories, Clippy and Format Checks

on:
  schedule:
    - cron: "0 4 * * *" # Daily at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  advisories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.88.0
      - name: Install cargo-deny
        run: cargo install --locked --version 0.18.9 cargo-deny
      - name: Check advisories
        run: cargo deny check advisories
  nightly_clippy:
    runs-on: ubuntu-latest
    name: "Nightly Lint and Format"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
      - name: Setup DLT tracing lib
        uses: eclipse-opensovd/dlt-tracing-lib/.github/actions/setup-dlt@main
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "34.1"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Format and Clippy - Nightly toolchain pinned
        continue-on-error: true
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@4700b71884074d194723fdb04a6c1a827b6f652b
        with:
          toolchain: nightly-2025-07-14
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: "false"
          fail-on-clippy-error: "false"
          clippy-deny-warnings: "false"
          clippy-features: "all-features"
          reporter: github-check
      - name: Format and Clippy - Nightly toolchain latest
        continue-on-error: true
        uses: eclipse-opensovd/cicd-workflows/rust-lint-and-format-action@4700b71884074d194723fdb04a6c1a827b6f652b
        with:
          toolchain: nightly
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-format-error: "false"
          fail-on-clippy-error: "false"
          clippy-deny-warnings: "false"
          clippy-features: "all-features"
          reporter: github-check
